### ISSUE TITLE
spine-c is now 3.2. 3.3  almost done.

### ISSUE THREAD

**Issue by pharan** [Chobolabs/spine-cpp#1]
Hey! Just thought you might be interested to know that the spine-c runtime has been compatible with 3.2 for a while. We're currently updating to 3.3 and it's almost done.

**Comment by iboB** [comment]
Unfortunately we can't spare the resources to do this in the very near future (It's not just a question of a couple of hours to do so). 

We will probably commence with the update in three weeks to a month.

**Comment by iboB** [comment]
Spine 3.4 is supported
