### ISSUE TITLE
Typos in TransformConstraint implementation.

### ISSUE THREAD

**Issue by Blttrr** [Chobolabs/spine-cpp#2]
There are few typos preventing usage of transform constraints:
1) In file `SkeletonJson.cpp`, line 334:
`transform.offsetTranslation.x = jtransform.get_safe_float_value_of_key(literal("y")) * m_scale;`
should be 
`transform.offsetTranslation.y = jtransform.get_safe_float_value_of_key(literal("y")) * m_scale;`

2) In file `Bone.cpp`, line 344:
`outWorld.y = local.x * c + local.y * d + worldPos.x;`
should be
`outWorld.y = local.x * c + local.y * d + worldPos.y;`

**Comment by iboB** [comment]
Thanks! Fixed
