### ISSUE TITLE
Missing sajson/sajson.h, and nowhere to be found

### ISSUE THREAD

**Issue by billkotsias** [Chobolabs/spine-cpp#7]
I have just tried to compile spine-cpp, but this header is missing. I have downloaded from here:
https://janbar.github.io/cppmyth/doxygen-dev-docs/html/sajson_8h_source.html

but it's a different version, the compiler is complaining that:
_**class "sajson::value" has no member "get_string_value"**_

I also had to change every **_sajon::..._** reference with **_::sajson::..._**

**Comment by billkotsias** [comment]
Just saw third_party folder in there, sorry

**Comment by iboB** [comment]
:) Yeah... we should definitely add some build instructions about the third party folder to avoid such confusion in the future

**Comment by billkotsias** [comment]
No build instructions needed unless you are a complete rookie, I simply wasn't paying attention :-)

BTW, I am new to GitHub and don't know if this is the right place to comment but... I intend to use spine-cpp with spine-cocos2dx. What rendering engine do you use it with?

**Comment by iboB** [comment]
We use our own proprietary engine, 

It seems it would be easy to modify the cocos2dx plugin by Esoteric Software to use spine-cpp. 

Keep in mind, though, that we haven't had much time to update spine-cpp in the last months, and although we do intend to do so towards the end of March or early April, right now the implementation has lagged somewhat in terms of features, compared to the official spine-c implementation by Esoteric.
